project: 
  type: website


website: 
  title: "Survival Analysis"
  navbar: 
    left: 
      - href: "index.qmd"
        text: About Me
      - href: "DataPrep.ipynb"
      - href: "EDA.ipynb"
        text: EDA

format: 
  html: 
    toc: true
    code-fold: true
    theme: lux
